---
# Example configuration for Code-Preloader

# List of repository paths to preload
# source_list:
#   - "path/to/repo1"
#   - "path/to/repo2"

# List of patterns to exclude (= ignore) during preloading
exclude_list:
  - ^\.git/.*
  - ^\.gitignore$
  - ^\.vagrant/.*
  - ^tmp.*
  - ^\.code_preloader.yml$
  - ".*\\.(png|jpeg|jpg|webp|pdf|mp4|mp3)$"

# List of patterns to include (= limit) during preloading
include_list: []
#  - ".*\\.(md|txt|markdown)$"

# Path to the output file (if null, output to STDOUT)
output_path: null

prompt:
  # Optional: Path to a file containing the prompt header
  header_path: null

  # Optional: Path to a file containing the prompt footer
  footer_path: null

  # Optional: Path to a file container a jinja template to structure the prompt
  template_path: null
